plugin:
    name: 'yamobile.blog::lang.plugin.name'
    description: 'yamobile.blog::lang.plugin.description'
    author: Ya-mobile
    icon: oc-icon-newspaper-o
    homepage: ''
navigation:
    blog:
        label: Блог
        url: yamobile/blog/category
        icon: icon-file
        sideMenu:
            category:
                label: Категории
                url: yamobile/blog/category
                icon: icon-list
