title: Category
modelClass: Yamobile\Blog\Models\Category
list: $/yamobile/blog/models/category/columns.yaml
recordUrl: 'yamobile/blog/category/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
